"use client";

import { useEffect, useState } from "react";
import { Plus, Save, Sparkles } from "lucide-react";
import { api, errorMessage } from "@/lib/api";
import type { PromptTemplate, RecommendationRule } from "@/lib/types";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";

export default function PromptsPage() {
  const [templates,setTemplates]=useState<PromptTemplate[]>([]); const [rules,setRules]=useState<RecommendationRule[]>([]); const [profile,setProfile]=useState(""); const [selected,setSelected]=useState("");
  const [history,setHistory]=useState<PromptTemplate[]>([]);
  const [error,setError]=useState(""); const [notice,setNotice]=useState(""); const [busy,setBusy]=useState(false);
  async function load(){setError("");try{const [p,r,u]=await Promise.all([api<PromptTemplate[]>("assistant/prompts"),api<RecommendationRule[]>("assistant/recommendation-rules"),api<{profileText:string}>("assistant/profile")]);setTemplates(p);setRules(r);setProfile(u.profileText);setSelected(current=>current||p[0]?.category||"");}catch(e){setError(errorMessage(e));}}
  useEffect(()=>{void load();},[]);
  useEffect(()=>{if(selected)api<PromptTemplate[]>(`assistant/prompts/${selected}/versions`).then(setHistory).catch(()=>setHistory([]));},[selected]);
  const active=templates.find(t=>t.category===selected);
  async function savePrompt(){if(!active)return;setBusy(true);setError("");try{const next=await api<PromptTemplate>(`assistant/prompts/${active.category}`,{method:"PUT",body:JSON.stringify({promptText:active.promptText})});setTemplates(rows=>[next,...rows.filter(r=>r.category!==next.category)]);setNotice(`${next.category.replaceAll("_"," ")} saved as version ${next.version}.`);}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
  async function saveProfile(){setBusy(true);setError("");try{await api("assistant/profile",{method:"PUT",body:JSON.stringify({profileText:profile})});setNotice("Your profile context was saved.");}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
  async function saveRules(){setBusy(true);setError("");try{const payload=rules.map(({category,keyword,weight,enabled})=>({category,keyword,weight,enabled}));const updated=await api<RecommendationRule[]>("assistant/recommendation-rules",{method:"PUT",body:JSON.stringify(payload)});setRules(updated);setNotice("Recommendation rules saved.");}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
  return <div className="space-y-6"><header><p className="text-xs font-semibold text-emerald-800 dark:text-emerald-400">Personalization</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">Prompts & profile</h1><p className="mt-2 text-sm text-slate-500">Tune the details and reusable templates behind your drafts.</p></header>
    {error&&<p role="alert" className="rounded-xl bg-rose-50 p-3 text-sm text-rose-700 dark:bg-rose-950/40 dark:text-rose-300">{error}</p>}{notice&&<p role="status" className="rounded-xl bg-emerald-50 p-3 text-sm text-emerald-900 dark:bg-emerald-950/50 dark:text-emerald-200">{notice}</p>}
    <Card><CardHeader><CardTitle className="text-base">My profile</CardTitle><CardDescription>Only use information you enter here. Drafts will not claim experience you haven’t provided.</CardDescription></CardHeader><CardContent><label className="form-label">Experience, skills, and current focus<textarea className="form-textarea mt-1.5 min-h-28" maxLength={5000} value={profile} onChange={e=>setProfile(e.target.value)} placeholder="e.g. Java backend engineer with experience in Spring Boot and AWS…"/></label><Button className="mt-3" disabled={busy} onClick={()=>void saveProfile()}><Save size={14}/>Save profile</Button></CardContent></Card>
    <Card><CardHeader><CardTitle className="text-base">Message prompt templates</CardTitle><CardDescription>Templates are stored and versioned in your database. Placeholders include {"{contactName}"}, {"{companyName}"}, {"{role}"}, {"{profileSummary}"}, {"{resumeLabel}"}, and {"{userName}"}.</CardDescription></CardHeader><CardContent className="space-y-4"><div className="flex flex-wrap gap-2">{templates.map(t=><button key={t.category} onClick={()=>setSelected(t.category)} className={`rounded-lg px-3 py-2 text-xs font-semibold ${selected===t.category?"bg-emerald-800 text-white":"bg-slate-100 text-slate-600 hover:bg-slate-200 dark:bg-slate-800 dark:text-slate-300"}`}>{t.category.replaceAll("_"," ")} <span className="opacity-60">v{t.version}</span></button>)}</div>{active&&<><label className="form-label">{active.category.replaceAll("_"," ")} · current version {active.version}<textarea aria-label="Prompt template text" className="form-textarea mt-1.5 min-h-48 font-normal" maxLength={12000} value={active.promptText} onChange={e=>setTemplates(rows=>rows.map(r=>r.category===active.category?{...r,promptText:e.target.value}:r))}/></label><div className="flex flex-wrap items-center justify-between gap-3"><p className="text-xs text-slate-400">Saving creates a new version and keeps earlier versions in the database.</p><Button disabled={busy} onClick={()=>void savePrompt()}><Save size={14}/>Save new version</Button></div><details className="rounded-xl bg-slate-50 p-3 text-xs dark:bg-slate-950"><summary className="cursor-pointer font-semibold text-slate-600 dark:text-slate-300">Version history ({history.length})</summary><div className="mt-3 flex flex-wrap gap-2">{history.map(version=><button key={version.id} onClick={()=>setTemplates(rows=>rows.map(r=>r.category===selected?{...r,promptText:version.promptText}:r))} className="rounded-lg border border-slate-200 px-2.5 py-1.5 text-slate-600 hover:bg-white dark:border-slate-700 dark:hover:bg-slate-900">Load v{version.version}</button>)}</div></details></>}</CardContent></Card>
    <Card><CardHeader><CardTitle className="text-base">Recommendation scoring rules</CardTitle><CardDescription>Matching terms add their weight to the contact recommendation. Keep scores grounded in saved contact details.</CardDescription></CardHeader><CardContent className="space-y-3">{rules.map((rule,index)=><div key={rule.id||`${rule.category}-${rule.keyword}-${index}`} className="grid gap-2 rounded-xl border border-slate-100 p-3 sm:grid-cols-[1fr_1fr_100px_auto_auto] sm:items-center dark:border-slate-800"><input aria-label="Rule category" className="form-select" value={rule.category} onChange={e=>setRules(rows=>rows.map((r,i)=>i===index?{...r,category:e.target.value}:r))}/><input aria-label="Matching keyword" className="form-select" value={rule.keyword} maxLength={100} onChange={e=>setRules(rows=>rows.map((r,i)=>i===index?{...r,keyword:e.target.value}:r))}/><label className="form-label">Weight<input aria-label="Weight" className="form-select mt-1" type="number" min={1} max={40} value={rule.weight} onChange={e=>setRules(rows=>rows.map((r,i)=>i===index?{...r,weight:Number(e.target.value)}:r))}/></label><label className="flex items-center gap-2 text-xs text-slate-600 dark:text-slate-300"><input type="checkbox" checked={rule.enabled} onChange={e=>setRules(rows=>rows.map((r,i)=>i===index?{...r,enabled:e.target.checked}:r))}/>Enabled</label><button aria-label="Remove rule" className="rounded-lg px-3 py-2 text-xs font-semibold text-rose-700 hover:bg-rose-50 dark:hover:bg-rose-950/50" onClick={()=>setRules(rows=>rows.filter((_,i)=>i!==index))}>Remove</button></div>)}<div className="flex flex-wrap gap-2"><Button variant="secondary" onClick={()=>setRules(rows=>[...rows,{category:"SKILL",keyword:"",weight:5,enabled:true}])}><Plus size={14}/>Add rule</Button><Button disabled={busy} onClick={()=>void saveRules()}><Sparkles size={14}/>Save rules</Button></div></CardContent></Card>
    <p className="text-center text-xs text-slate-400">No external language model is configured in this phase. Message drafts currently use these editable, database-backed templates and your saved context.</p>
  </div>;
}
