"use client";

import { useEffect, useState } from "react";
import { BarChart3, Clock3, MessageCircle, RefreshCw, Trophy } from "lucide-react";
import { api, errorMessage } from "@/lib/api";
import type { NetworkingAnalytics } from "@/lib/types";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";

function Metric({label,value,caption}:{label:string;value:string;caption:string}){return <Card><CardContent className="p-5"><p className="text-xs font-medium text-slate-500">{label}</p><p className="mt-3 text-3xl font-semibold tracking-tight">{value}</p><p className="mt-2 text-xs text-slate-400">{caption}</p></CardContent></Card>}
function Groups({title,description,rows}:{title:string;description:string;rows:NetworkingAnalytics["topCompanies"]}){return <Card><CardHeader><CardTitle className="text-base">{title}</CardTitle><CardDescription>{description}</CardDescription></CardHeader><CardContent className="space-y-3">{rows.length?rows.map(row=><div key={row.name} className="flex items-center gap-3"><span className="min-w-0 flex-1 truncate text-sm font-medium">{row.name}</span><span className="text-xs text-slate-400">{row.replies}/{row.count} replies</span><span className="w-12 text-right text-xs font-semibold text-emerald-800 dark:text-emerald-300">{row.responseRate}%</span></div>):<p className="py-4 text-sm text-slate-500">Not enough outreach data yet.</p>}</CardContent></Card>}
export default function NetworkingAnalyticsPage(){const[data,setData]=useState<NetworkingAnalytics|null>(null);const[error,setError]=useState("");const[loading,setLoading]=useState(true);async function load(){setLoading(true);setError("");try{setData(await api<NetworkingAnalytics>("assistant/analytics"));}catch(e){setError(errorMessage(e));}finally{setLoading(false);}}useEffect(()=>{void load();},[]);
return <div className="space-y-6"><header><p className="text-xs font-semibold text-emerald-800 dark:text-emerald-400">Your networking activity</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">Networking analytics</h1><p className="mt-2 text-sm text-slate-500">Use your tracked conversations to learn what’s working.</p></header>{error&&<div className="rounded-xl bg-rose-50 p-4 text-sm text-rose-700">{error}<Button variant="secondary" size="sm" className="ml-3" onClick={()=>void load()}>Try again</Button></div>}{loading?<Card><CardContent className="flex items-center justify-center gap-2 p-10 text-sm text-slate-500"><RefreshCw size={16} className="animate-spin"/>Calculating analytics…</CardContent></Card>:data&&<><section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Metric label="Response rate" value={`${data.responseRate}%`} caption="Contacts who replied"/><Metric label="Referral rate" value={`${data.referralRate}%`} caption="Contacts resulting in a referral"/><Metric label="Interview rate" value={`${data.interviewRate}%`} caption="Contacts associated with interviews"/><Metric label="Offer rate" value={`${data.offerRate}%`} caption="Tracked offers across outreach"/><Metric label="Average reply time" value={data.averageReplyHours?`${data.averageReplyHours}h`:"—"} caption="From first recorded message to reply"/></section><section className="grid gap-5 lg:grid-cols-2"><Groups title="Top companies" description="Companies ranked by replies, then outreach volume." rows={data.topCompanies}/><Groups title="Top roles" description="Roles with the strongest response rate." rows={data.topRoles}/></section><section><div className="mb-3"><h2 className="text-base font-semibold">What’s resonating</h2><p className="mt-1 text-sm text-slate-500">Derived from the resume and message versions you marked as sent.</p></div><div className="grid gap-3 sm:grid-cols-3"><Card><CardContent className="p-5"><Trophy className="text-emerald-800" size={18}/><p className="mt-4 text-xs text-slate-500">Most successful resume</p><p className="mt-1 text-sm font-semibold">{data.mostSuccessfulResume||"Not enough data yet"}</p></CardContent></Card><Card><CardContent className="p-5"><MessageCircle className="text-violet-700" size={18}/><p className="mt-4 text-xs text-slate-500">Best performing message</p><p className="mt-1 text-sm font-semibold">{data.bestPerformingMessage||"Not enough data yet"}</p></CardContent></Card><Card><CardContent className="p-5"><BarChart3 className="text-sky-700" size={18}/><p className="mt-4 text-xs text-slate-500">Most responsive contact type</p><p className="mt-1 text-sm font-semibold">{data.mostResponsiveContactType||"Not enough data yet"}</p></CardContent></Card></div></section></>}</div>}
