"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowUpRight, Building2, MapPin, RefreshCw, Sparkles, UsersRound } from "lucide-react";
import { api, errorMessage } from "@/lib/api";
import type { AssistantContact, Company, GeneratedMessage, OpportunityQueue, Page, Resume } from "@/lib/types";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { titleCase } from "@/lib/utils";

function ContactCard({ contact, onGenerate, busy }: { contact: AssistantContact; onGenerate: (contact: AssistantContact, followUp: boolean) => void; busy: boolean }) {
  return <article className="rounded-xl border border-slate-100 p-4 dark:border-slate-800"><div className="flex flex-wrap items-start justify-between gap-3"><div className="min-w-0"><p className="font-semibold">{contact.name}</p><p className="mt-1 text-xs text-slate-500">{contact.designation || "Role not added"}{contact.companyName ? ` · ${contact.companyName}` : ""}</p>{contact.location && <p className="mt-1 flex items-center gap-1 text-[11px] text-slate-400"><MapPin size={12} />{contact.location}</p>}</div><span className="rounded-full bg-emerald-50 px-2.5 py-1 text-xs font-semibold text-emerald-900 dark:bg-emerald-950 dark:text-emerald-200">{contact.recommendationScore}% match</span></div><p className="mt-3 text-xs leading-5 text-slate-500">{contact.reasoning}</p><div className="mt-4 flex flex-wrap items-center gap-2"><span className="rounded-lg bg-slate-50 px-2.5 py-1.5 text-[11px] text-slate-600 dark:bg-slate-800 dark:text-slate-300">{titleCase(contact.status)}</span>{contact.needsFollowUp && <Button size="sm" variant="secondary" disabled={busy} onClick={() => onGenerate(contact,true)}>Draft follow-up</Button>}<Button size="sm" disabled={busy} onClick={() => onGenerate(contact,false)}><Sparkles size={14} /> Prepare outreach</Button>{contact.linkedinUrl && <a href={contact.linkedinUrl} target="_blank" rel="noreferrer" className="inline-flex h-9 items-center gap-1 rounded-xl px-3 text-xs font-semibold text-slate-500 hover:bg-slate-100 dark:hover:bg-slate-800">Open profile <ArrowUpRight size={13} /></a>}</div></article>;
}

export default function OpportunitiesPage() {
  const router = useRouter();
  const [queue,setQueue]=useState<OpportunityQueue>({contacts:[],suggestedContacts:[],suggestedCompanies:[]});
  const [companies,setCompanies]=useState<Company[]>([]); const [resumes,setResumes]=useState<Resume[]>([]);
  const [companyId,setCompanyId]=useState(""); const [role,setRole]=useState(""); const [status,setStatus]=useState(""); const [location,setLocation]=useState(""); const [priority,setPriority]=useState("");
  const [resumeId,setResumeId]=useState(""); const [busyId,setBusyId]=useState(""); const [error,setError]=useState(""); const [loading,setLoading]=useState(true);
  useEffect(()=>{ api<Page<Company>>("companies?size=100&sort=name&direction=asc").then(r=>setCompanies(r.content)).catch(()=>setCompanies([])); api<Page<Resume>>("resumes?size=100").then(r=>setResumes(r.content)).catch(()=>setResumes([])); },[]);
  useEffect(()=>{ const q=new URLSearchParams(); if(companyId)q.set("companyId",companyId); if(role)q.set("role",role); if(status)q.set("status",status); if(location)q.set("location",location); if(priority)q.set("priority",priority); setLoading(true); setError(""); api<OpportunityQueue>(`assistant/opportunities?${q}`).then(setQueue).catch(e=>setError(errorMessage(e))).finally(()=>setLoading(false)); },[companyId,role,status,location,priority]);
  async function generate(contact:AssistantContact,followUp:boolean){ setBusyId(contact.id);setError(""); try { const drafts=await api<GeneratedMessage[]>(followUp?"assistant/follow-up/generate":"assistant/messages/generate",{method:"POST",body:JSON.stringify({contactId:contact.id,resumeId:resumeId||null,role:role||contact.designation||null})}); if(drafts.length)router.push(`/review?contact=${encodeURIComponent(contact.id)}`); }catch(e){setError(errorMessage(e));}finally{setBusyId("");} }
  const onGenerate=(contact:AssistantContact,followUp:boolean)=>void generate(contact,followUp);
  return <div className="space-y-6"><header><p className="text-xs font-semibold text-emerald-800 dark:text-emerald-400">AI networking assistant</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">Today’s Opportunities</h1><p className="mt-2 text-sm text-slate-500">Review your network and prepare outreach for you to send yourself.</p></header>
    <Card><CardHeader><CardTitle className="text-base">Find the next conversation</CardTitle><CardDescription>Filter saved people and companies, then review the recommendations.</CardDescription></CardHeader><CardContent><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><label className="form-label">Company<select className="form-select mt-1.5" value={companyId} onChange={e=>setCompanyId(e.target.value)}><option value="">All companies</option>{companies.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="form-label">Role<Input className="mt-1.5" value={role} onChange={e=>setRole(e.target.value)} placeholder="Backend engineer" /></label><label className="form-label">Status<select className="form-select mt-1.5" value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option>{["NOT_CONTACTED","MESSAGE_READY","CONTACTED","REPLIED","REFERRED","INTERVIEW","REJECTED","NO_RESPONSE"].map(s=><option key={s} value={s}>{titleCase(s)}</option>)}</select></label><label className="form-label">Location<Input className="mt-1.5" value={location} onChange={e=>setLocation(e.target.value)} placeholder="City or region" /></label><label className="form-label">Company priority<select className="form-select mt-1.5" value={priority} onChange={e=>setPriority(e.target.value)}><option value="">Any priority</option>{[5,4,3,2,1].map(p=><option key={p} value={p}>{p} · {p===5?"Top":p===1?"Low":"Priority"}</option>)}</select></label></div><label className="form-label mt-4 block max-w-sm">Resume to include<select className="form-select mt-1.5" value={resumeId} onChange={e=>setResumeId(e.target.value)}><option value="">Recommend the closest resume</option>{resumes.map(r=><option key={r.id} value={r.id}>{r.label}</option>)}</select></label></CardContent></Card>
    {error&&<p role="alert" className="rounded-xl bg-rose-50 p-3 text-sm text-rose-700 dark:bg-rose-950/40 dark:text-rose-300">{error}</p>}
    <div className="grid gap-5 xl:grid-cols-[1fr_0.72fr]"><Card><CardHeader className="flex-row items-center justify-between"><div><CardTitle className="text-base">Suggested contacts</CardTitle><CardDescription className="mt-1">Ranked from your saved contacts and your editable scoring rules.</CardDescription></div><UsersRound size={18} className="text-emerald-700" /></CardHeader><CardContent className="space-y-3">{loading?<p className="py-8 text-center text-sm text-slate-400"><RefreshCw className="mx-auto mb-2 animate-spin" size={17}/>Loading your network…</p>:queue.suggestedContacts.length?queue.suggestedContacts.map(c=><ContactCard key={c.id} contact={c} onGenerate={onGenerate} busy={busyId===c.id}/>):<p className="rounded-xl bg-slate-50 p-5 text-sm text-slate-500 dark:bg-slate-950">No new contacts match these filters yet. Saved contacts still appear below.</p>}</CardContent></Card>
    <Card><CardHeader><CardTitle className="text-base">Suggested companies</CardTitle><CardDescription>Priority companies without a linked contact.</CardDescription></CardHeader><CardContent className="space-y-2">{queue.suggestedCompanies.length?queue.suggestedCompanies.map(c=><div key={c.id} className="flex items-center gap-3 rounded-xl bg-slate-50 p-3 dark:bg-slate-950"><Building2 size={17} className="shrink-0 text-emerald-800"/><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{c.name}{c.dreamCompany?" · Dream company":""}</p><p className="text-[11px] text-slate-500">Priority {c.priority} · {titleCase(c.applicationStatus)}</p></div></div>):<p className="py-5 text-sm text-slate-500">Add companies or link contacts to see suggestions here.</p>}</CardContent></Card></div>
    <Card><CardHeader><CardTitle className="text-base">Saved contacts</CardTitle><CardDescription>Follow-ups stay visible here until they reply or you update their status.</CardDescription></CardHeader><CardContent className="space-y-3">{!loading&&queue.contacts.length?queue.contacts.map(c=><ContactCard key={c.id} contact={c} onGenerate={onGenerate} busy={busyId===c.id}/>):!loading?<p className="py-8 text-center text-sm text-slate-500">No saved contacts match these filters.</p>:null}</CardContent></Card>
    <p className="text-center text-xs text-slate-400">Drafts never leave Referral CRM automatically. You decide what to copy, where to open, and when to mark sent.</p>
  </div>;
}
