"use client";

import { useEffect, useState } from "react";
import { useSearchParams } from "next/navigation";
import { Check, Clipboard, ExternalLink, FileText, RefreshCw, Save, ShieldCheck } from "lucide-react";
import { api, errorMessage } from "@/lib/api";
import type { GeneratedMessage } from "@/lib/types";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { titleCase } from "@/lib/utils";

export default function ReviewPage() {
  const search=useSearchParams(); const contactFilter=search.get("contact");
  const [messages,setMessages]=useState<GeneratedMessage[]>([]); const [editing,setEditing]=useState<string|null>(null); const [filter,setFilter]=useState("REVIEW");
  const [channels,setChannels]=useState<Record<string,string>>({}); const [error,setError]=useState(""); const [notice,setNotice]=useState(""); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState("");
  async function load(){setLoading(true);setError("");try{const rows=await api<GeneratedMessage[]>("assistant/messages");setMessages(rows.filter(m=>m.status!=="SENT"&&(!contactFilter||m.contactId===contactFilter)));}catch(e){setError(errorMessage(e));}finally{setLoading(false);}}
  useEffect(()=>{void load();},[contactFilter]);
  function replace(message:GeneratedMessage){setMessages(current=>[message,...current.filter(m=>m.id!==message.id&&!(m.contactId===message.contactId&&m.variant===message.variant&&m.version<message.version))]);}
  async function save(message:GeneratedMessage){setBusy(message.id);setError("");try{const updated=await api<GeneratedMessage>(`assistant/messages/${message.id}`,{method:"PUT",body:JSON.stringify({messageText:message.messageText})});replace(updated);setEditing(null);setNotice(`Saved as version ${updated.version}.`);}catch(e){setError(errorMessage(e));}finally{setBusy("");}}
  async function approve(message:GeneratedMessage){setBusy(message.id);setError("");try{replace(await api<GeneratedMessage>(`assistant/messages/${message.id}/approve`,{method:"POST"}));setNotice("Draft approved for your review.");}catch(e){setError(errorMessage(e));}finally{setBusy("");}}
  async function markSent(message:GeneratedMessage){setBusy(message.id);setError("");try{await api<GeneratedMessage>(`assistant/messages/${message.id}/sent`,{method:"POST",body:JSON.stringify({channel:channels[message.id]||message.channel})});setMessages(current=>current.filter(m=>m.id!==message.id));setNotice("Outreach marked sent. No message was sent by the app.");}catch(e){setError(errorMessage(e));}finally{setBusy("");}}
  async function copy(message:GeneratedMessage){try{await navigator.clipboard.writeText(message.messageText);setNotice("Copied. Review it and send manually when ready.");}catch{setError("Clipboard access is unavailable. Select and copy the draft text manually.");}}
  const shown=messages.filter(m=>filter==="REVIEW"?m.status!=="SENT":m.status===filter);
  return <div className="space-y-6"><header className="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><p className="text-xs font-semibold text-emerald-800 dark:text-emerald-400">Human-approved outreach</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">Outreach review queue</h1><p className="mt-2 text-sm text-slate-500">Edit each draft, approve it, then copy and send it yourself.</p></div><label className="form-label sm:w-52">Show<select className="form-select mt-1.5" value={filter} onChange={e=>setFilter(e.target.value)}><option value="REVIEW">Needs review</option><option value="DRAFT">Drafts</option><option value="APPROVED">Approved</option></select></label></header>
    {error&&<p role="alert" className="rounded-xl bg-rose-50 p-3 text-sm text-rose-700 dark:bg-rose-950/40 dark:text-rose-300">{error}</p>}{notice&&<p role="status" className="rounded-xl bg-emerald-50 p-3 text-sm text-emerald-900 dark:bg-emerald-950/50 dark:text-emerald-200">{notice}</p>}
    {loading?<Card><CardContent className="p-10 text-center text-sm text-slate-500"><RefreshCw className="mx-auto mb-3 animate-spin" size={18}/>Loading drafts…</CardContent></Card>:shown.length?shown.map(message=><Card key={message.id}><CardHeader className="flex-row flex-wrap items-start justify-between"><div><CardTitle className="text-base">{message.contactName}</CardTitle><CardDescription className="mt-1">{message.role||"Role not set"}{message.companyName?` · ${message.companyName}`:""} · {titleCase(message.variant)} · Version {message.version}</CardDescription></div><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${message.status==="APPROVED"?"bg-emerald-100 text-emerald-900 dark:bg-emerald-950 dark:text-emerald-200":"bg-amber-50 text-amber-900 dark:bg-amber-950 dark:text-amber-200"}`}>{titleCase(message.status)}</span></CardHeader><CardContent className="space-y-4">
      <div className="grid gap-3 sm:grid-cols-2"><div className="rounded-xl bg-slate-50 p-3 dark:bg-slate-950"><p className="text-[11px] font-semibold uppercase tracking-wide text-slate-400">Recommendation</p><p className="mt-1 text-sm font-semibold">{message.recommendationScore}% match</p><p className="mt-1 text-xs leading-5 text-slate-500">{message.recommendationReason}</p></div><div className="rounded-xl bg-slate-50 p-3 dark:bg-slate-950"><p className="flex items-center gap-1.5 text-[11px] font-semibold uppercase tracking-wide text-slate-400"><FileText size={13}/> Resume</p><p className="mt-1 text-sm font-semibold">{message.resumeLabel||"No resume selected"}</p><p className="mt-1 text-xs leading-5 text-slate-500">{message.resumeReason}</p></div></div>
      {editing===message.id?<textarea aria-label={`Edit message for ${message.contactName}`} className="form-textarea min-h-36" value={message.messageText} onChange={e=>setMessages(rows=>rows.map(row=>row.id===message.id?{...row,messageText:e.target.value}:row))}/>:<div className="whitespace-pre-wrap rounded-xl border border-slate-200 p-4 text-sm leading-6 dark:border-slate-700">{message.messageText}</div>}
      <div className="flex flex-wrap items-center gap-2"><select aria-label={`Channel for ${message.contactName}`} className="form-select w-auto min-w-40" value={channels[message.id]||message.channel} onChange={e=>setChannels(current=>({...current,[message.id]:e.target.value}))}><option value="LINKEDIN">LinkedIn</option><option value="EMAIL">Email</option><option value="REFERRAL_PORTAL">Referral portal</option><option value="OTHER">Other</option></select>{editing===message.id?<Button size="sm" disabled={busy===message.id} onClick={()=>void save(message)}><Save size={14}/>Save as new version</Button>:<Button size="sm" variant="secondary" onClick={()=>setEditing(message.id)}>Edit</Button>}<Button size="sm" variant="secondary" onClick={()=>void copy(message)}><Clipboard size={14}/>Copy</Button>{message.linkedinUrl&&<a href={message.linkedinUrl} target="_blank" rel="noreferrer" className="inline-flex h-9 items-center gap-1.5 rounded-xl border border-slate-200 px-3 text-xs font-semibold text-slate-700 hover:bg-slate-50 dark:border-slate-700 dark:text-slate-200 dark:hover:bg-slate-800"><ExternalLink size={14}/>Open profile</a>}{message.status==="DRAFT"&&editing!==message.id&&<Button size="sm" variant="secondary" disabled={busy===message.id} onClick={()=>void approve(message)}><ShieldCheck size={14}/>Approve</Button>}{message.status==="APPROVED"&&<Button size="sm" disabled={busy===message.id} onClick={()=>void markSent(message)}><Check size={14}/>Mark as Sent</Button>}</div>
      <p className="text-[11px] text-slate-400">The app only prepares and records this draft. It never sends messages or automates profile actions.</p>
    </CardContent></Card>):<Card><CardContent className="p-12 text-center"><ShieldCheck className="mx-auto text-emerald-700" size={24}/><p className="mt-3 font-semibold">Your review queue is clear</p><p className="mt-1 text-sm text-slate-500">Prepare outreach from Today’s Opportunities. Every message stays a draft until you review it.</p></CardContent></Card>}
  </div>;
}
