"use client";

import { useEffect, useState, type FormEvent } from "react";
import { BriefcaseBusiness, FileText, FolderKanban, Sparkles, UploadCloud } from "lucide-react";
import { api, errorMessage } from "@/lib/api";
import type { Page, Resume, ResumeDocumentInfo, ResumeIntelligence, ResumeUploadResult } from "@/lib/types";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";

export default function ResumeIntelligencePage(){
  const [resumes,setResumes]=useState<Resume[]>([]);const [selected,setSelected]=useState("");const [profile,setProfile]=useState<ResumeIntelligence>();const [documents,setDocuments]=useState<ResumeDocumentInfo[]>([]);
  const [label,setLabel]=useState("");const [file,setFile]=useState<File>();const [busy,setBusy]=useState(false);const [loading,setLoading]=useState(true);const [error,setError]=useState("");
  async function loadList(){setLoading(true);try{const page=await api<Page<Resume>>("resumes?page=0&size=100&sort=createdAt&direction=desc");setResumes(page.content);if(!selected&&page.content[0])setSelected(page.content[0].id);}catch(e){setError(errorMessage(e));}finally{setLoading(false);}}
  async function loadResume(id:string){setSelected(id);setProfile(undefined);setError("");try{const [data,docs]=await Promise.all([api<ResumeIntelligence>(`resumes/${id}/intelligence`),api<ResumeDocumentInfo[]>(`resumes/${id}/documents`)]);setProfile(data);setDocuments(docs);}catch(e){setError(errorMessage(e));}}
  useEffect(()=>{void loadList();},[]);
  useEffect(()=>{if(selected)void loadResume(selected);},[selected]);
  async function upload(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget;if(!file)return;setBusy(true);setError("");try{const body=new FormData();body.set("label",label.trim());body.set("file",file);const response=await api<ResumeUploadResult>("resumes/upload",{method:"POST",body});const page=await api<Page<Resume>>("resumes?page=0&size=100&sort=createdAt&direction=desc");setResumes(page.content);setSelected(response.resume.id);setProfile(response.intelligence);setDocuments([response.document,...documents]);setLabel("");setFile(undefined);form.reset();}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
  return <div className="space-y-6">
    <header><p className="text-xs font-semibold text-emerald-800 dark:text-emerald-400">Resume intelligence</p><h1 className="mt-1 text-[29px] font-semibold tracking-[-0.04em]">Your resume library</h1><p className="mt-1.5 text-sm text-slate-500">Upload a PDF to extract selectable text, skills, project details, and experience for job comparisons.</p></header>
    {error&&<p role="alert" className="rounded-xl bg-rose-50 px-4 py-3 text-sm text-rose-700 dark:bg-rose-950/50 dark:text-rose-300">{error}</p>}
    <Card><CardContent className="p-5"><div className="mb-4 flex items-center gap-2"><UploadCloud size={17} className="text-emerald-800 dark:text-emerald-400"/><div><h2 className="text-sm font-semibold">Upload resume PDF</h2><p className="mt-1 text-xs text-slate-500">Up to 10 MB. The PDF stays in private local storage; extracted text is saved separately.</p></div></div><form onSubmit={upload} className="grid gap-3 md:grid-cols-[minmax(180px,0.8fr)_minmax(220px,1fr)_minmax(220px,1.4fr)_auto] md:items-end"><label className="form-label">Resume label<Input required maxLength={120} value={label} onChange={e=>setLabel(e.target.value)} placeholder="Java Backend"/></label><label className="form-label">PDF file<input required type="file" accept="application/pdf,.pdf" onChange={e=>setFile(e.target.files?.[0])} className="block h-10 w-full rounded-xl border border-slate-200 bg-white px-3 py-2 text-xs text-slate-600 file:mr-3 file:border-0 file:bg-transparent file:text-xs file:font-semibold dark:border-slate-700 dark:bg-slate-900 dark:text-slate-300"/></label><p className="self-center text-xs text-slate-400">Skills and sections are detected locally with rules. Review extracted details before using them.</p><Button type="submit" disabled={busy||!file}>{busy?"Extracting…":"Upload and analyze"}</Button></form></CardContent></Card>
    {resumes.length>0&&<div className="flex items-center gap-3"><label htmlFor="resume-select" className="text-xs font-semibold text-slate-500">Resume</label><select id="resume-select" className="form-select max-w-sm" value={selected} onChange={e=>setSelected(e.target.value)}>{resumes.map(r=><option key={r.id} value={r.id}>{r.label} · {r.fileName}</option>)}</select></div>}
    {loading?<Card><CardContent className="p-8 text-sm text-slate-500">Loading your resume library…</CardContent></Card>:profile?<div className="space-y-5">
      <div className="grid gap-3 sm:grid-cols-3"><Card><CardContent className="flex items-center gap-3 p-4"><span className="grid size-10 place-items-center rounded-xl bg-emerald-50 text-emerald-800 dark:bg-emerald-950 dark:text-emerald-300"><Sparkles size={18}/></span><div><p className="text-2xl font-semibold">{profile.skills.length}</p><p className="text-xs text-slate-500">Detected skills</p></div></CardContent></Card><Card><CardContent className="flex items-center gap-3 p-4"><span className="grid size-10 place-items-center rounded-xl bg-sky-50 text-sky-800 dark:bg-sky-950 dark:text-sky-300"><FolderKanban size={18}/></span><div><p className="text-2xl font-semibold">{profile.projects.length}</p><p className="text-xs text-slate-500">Projects parsed</p></div></CardContent></Card><Card><CardContent className="flex items-center gap-3 p-4"><span className="grid size-10 place-items-center rounded-xl bg-violet-50 text-violet-800 dark:bg-violet-950 dark:text-violet-300"><BriefcaseBusiness size={18}/></span><div><p className="text-2xl font-semibold">{profile.experience.length}</p><p className="text-xs text-slate-500">Experience entries</p></div></CardContent></Card></div>
      <Card><CardContent className="p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-sm font-semibold">Skills found in {profile.resumeLabel}</h2><p className="mt-1 text-xs text-slate-500">Rule-based text extraction may miss or misclassify skills; verify these before matching.</p></div><a href={`/jobs`} className="text-xs font-semibold text-emerald-800 dark:text-emerald-400">Review job matches</a></div><div className="mt-4 flex flex-wrap gap-2">{profile.skills.length?profile.skills.map(skill=><Badge key={skill}>{skill}</Badge>):<p className="text-sm text-slate-500">No catalog skills detected. You can add verified skills from the Jobs page.</p>}</div></CardContent></Card>
      <section className="grid gap-5 xl:grid-cols-2"><Card><CardContent className="p-5"><h2 className="flex items-center gap-2 text-sm font-semibold"><FolderKanban size={16}/> Projects</h2><div className="mt-3 space-y-3">{profile.projects.length?profile.projects.map(project=><article key={project.id} className="rounded-xl border border-slate-200 p-4 dark:border-slate-800"><h3 className="text-sm font-semibold">{project.name}</h3>{project.description&&<p className="mt-1 text-xs leading-5 text-slate-500">{project.description}</p>}<div className="mt-2 flex flex-wrap gap-1.5">{project.technologies.map(t=><Badge key={t}>{t}</Badge>)}</div></article>):<p className="rounded-xl bg-slate-50 p-4 text-sm text-slate-500 dark:bg-slate-950">No projects section was confidently detected.</p>}</div></CardContent></Card><Card><CardContent className="p-5"><h2 className="flex items-center gap-2 text-sm font-semibold"><BriefcaseBusiness size={16}/> Experience</h2><div className="mt-3 space-y-3">{profile.experience.length?profile.experience.map(item=><article key={item.id} className="rounded-xl border border-slate-200 p-4 dark:border-slate-800"><div className="flex flex-wrap justify-between gap-2"><h3 className="text-sm font-semibold">{item.role||"Role"}{item.company?` · ${item.company}`:""}</h3>{item.duration&&<span className="text-xs text-slate-400">{item.duration}</span>}</div>{item.description&&<p className="mt-2 text-xs leading-5 text-slate-500">{item.description}</p>}</article>):<p className="rounded-xl bg-slate-50 p-4 text-sm text-slate-500 dark:bg-slate-950">No experience section was confidently detected. Scanned PDFs are not OCR processed.</p>}</div></CardContent></Card></section>
      {documents.length>0&&<Card><CardContent className="flex items-center justify-between gap-3 p-4"><div className="flex items-center gap-3"><FileText size={17} className="text-slate-400"/><div><p className="text-sm font-medium">{documents[0].fileName}</p><p className="text-xs text-slate-500">PDF · {(documents[0].fileSize/1024).toFixed(0)} KB</p></div></div><a href={`/api/backend/resumes/${selected}/documents/${documents[0].id}/download`} className="text-xs font-semibold text-emerald-800 dark:text-emerald-400">Download PDF</a></CardContent></Card>}
      <details className="rounded-xl border border-slate-200 bg-white p-4 dark:border-slate-800 dark:bg-slate-900"><summary className="cursor-pointer text-sm font-semibold">View extracted text</summary><pre className="mt-3 max-h-96 overflow-auto whitespace-pre-wrap text-xs leading-5 text-slate-600 dark:text-slate-300">{profile.extractedText||"No extracted text"}</pre></details>
    </div>:!resumes.length?<Card><CardContent className="py-14 text-center"><FileText size={23} className="mx-auto text-emerald-800 dark:text-emerald-400"/><h2 className="mt-3 text-sm font-semibold">Your resume library is empty</h2><p className="mt-1 text-xs text-slate-500">Upload a text-based PDF to extract your resume profile.</p></CardContent></Card>:null}
  </div>;
}
