"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { ArrowRight, Check, FileSearch, Sparkles, X } from "lucide-react";
import { api, errorMessage } from "@/lib/api";
import type { JobAnalysisResult, JobOpportunity, Page } from "@/lib/types";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";

export default function JobAnalysisPage(){
  const [jobs,setJobs]=useState<JobOpportunity[]>([]);const [jobId,setJobId]=useState("");const [result,setResult]=useState<JobAnalysisResult>();const [busy,setBusy]=useState(false);const [loading,setLoading]=useState(true);const [error,setError]=useState("");
  useEffect(()=>{api<Page<JobOpportunity>>("jobs?page=0&size=100&sort=updatedAt&direction=desc").then(page=>{setJobs(page.content);if(page.content[0])setJobId(page.content[0].id);}).catch(e=>setError(errorMessage(e))).finally(()=>setLoading(false));},[]);
  useEffect(()=>{if(!jobId)return;setResult(undefined);api<JobAnalysisResult[]>(`jobs/${jobId}/analysis`).then(history=>{if(history[0])setResult(history[0]);}).catch(e=>setError(errorMessage(e)));},[jobId]);
  async function analyze(){if(!jobId)return;setBusy(true);setError("");try{const response=await api<JobAnalysisResult>(`jobs/${jobId}/analysis`,{method:"POST"});setResult(response);}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
  async function updateSuggestion(id:string,status:"APPLIED"|"IGNORED"){if(!jobId)return;try{const updated=await api<JobAnalysisResult["suggestions"][number]>(`jobs/${jobId}/suggestions/${id}`,{method:"PATCH",body:JSON.stringify({status})});setResult(current=>current?{...current,suggestions:current.suggestions.map(s=>s.id===id?updated:s)}:current);}catch(e){setError(errorMessage(e));}}
  const selected=jobs.find(j=>j.id===jobId);
  return <div className="space-y-6">
    <header><p className="text-xs font-semibold text-emerald-800 dark:text-emerald-400">Job analysis</p><h1 className="mt-1 text-[29px] font-semibold tracking-[-0.04em]">Resume fit for each role</h1><p className="mt-1.5 text-sm text-slate-500">Compare resume evidence with job requirements and review improvement ideas before changing your resume.</p></header>
    {error&&<p role="alert" className="rounded-xl bg-rose-50 px-4 py-3 text-sm text-rose-700 dark:bg-rose-950/50 dark:text-rose-300">{error}</p>}
    <Card><CardContent className="flex flex-col gap-3 p-4 sm:flex-row sm:items-end"><label className="form-label min-w-0 flex-1">Job<select disabled={loading||!jobs.length} className="form-select" value={jobId} onChange={e=>setJobId(e.target.value)}>{jobs.map(j=><option key={j.id} value={j.id}>{j.title}</option>)}</select></label><Button onClick={()=>void analyze()} disabled={!jobId||busy}><Sparkles size={15}/>{busy?"Analyzing…":"Analyze resume match"}</Button></CardContent></Card>
    {result&&<div className="space-y-5"><Card><CardContent className="grid gap-5 p-5 sm:grid-cols-[auto_1fr] sm:items-center"><div className="grid size-24 place-items-center rounded-full border-[7px] border-emerald-100 text-center dark:border-emerald-950"><span><span className="block text-2xl font-bold text-emerald-900 dark:text-emerald-200">{result.matchScore}%</span><span className="text-[10px] text-slate-500">match</span></span></div><div><div className="flex flex-wrap items-center gap-2"><h2 className="text-lg font-semibold">{result.jobTitle}</h2><Badge>{result.experienceMatch}% experience fit</Badge></div><p className="mt-2 text-sm text-slate-600 dark:text-slate-300">Recommended resume: <strong>{result.recommendedResume??"Upload a resume"}</strong></p><p className="mt-1 text-xs text-slate-500">{result.resumeReason}</p><p className="mt-3 text-sm text-slate-600 dark:text-slate-300">{result.recommendations[0]}</p></div></CardContent></Card>
      <section className="grid gap-4 xl:grid-cols-2"><Card><CardContent className="p-5"><h2 className="text-sm font-semibold">Skills found</h2><div className="mt-3 flex flex-wrap gap-2">{result.matchingSkills.length?result.matchingSkills.map(s=><Badge key={s} tone="REFERRED">{s}</Badge>):<p className="text-sm text-slate-500">No matching skills were found in parsed resume evidence.</p>}</div>{result.strengths.length>0&&<ul className="mt-4 space-y-2 text-xs leading-5 text-slate-600 dark:text-slate-300">{result.strengths.map(s=><li key={s}>• {s}</li>)}</ul>}</CardContent></Card><Card><CardContent className="p-5"><h2 className="text-sm font-semibold">Skills to review</h2><div className="mt-3 flex flex-wrap gap-2">{result.missingSkills.length?result.missingSkills.map(s=><Badge key={s} tone="REJECTED">{s}</Badge>):<p className="text-sm text-slate-500">No missing skills among the listed requirements.</p>}</div>{result.weaknesses.length>0&&<ul className="mt-4 space-y-2 text-xs leading-5 text-slate-600 dark:text-slate-300">{result.weaknesses.map(s=><li key={s}>• {s}</li>)}</ul>}</CardContent></Card></section>
      <Card><CardContent className="p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-sm font-semibold">Resume improvement suggestions</h2><p className="mt-1 text-xs text-slate-500">Suggestions are evidence-based prompts. Add only experience and results that are true.</p></div>{selected&&<Link href="/interview-prep" className="inline-flex items-center gap-1 text-xs font-semibold text-emerald-800 dark:text-emerald-400">Interview preparation <ArrowRight size={14}/></Link>}</div><div className="mt-4 space-y-3">{result.suggestions.map(s=><article key={s.id} className="flex flex-col gap-3 rounded-xl border border-slate-200 p-4 sm:flex-row sm:items-start dark:border-slate-800"><div className="min-w-0 flex-1"><p className="text-sm leading-6">{s.suggestion}</p><Badge className="mt-2">{s.status}</Badge></div>{s.status==="PENDING"&&<div className="flex gap-2"><Button size="sm" variant="secondary" onClick={()=>void updateSuggestion(s.id,"APPLIED")}><Check size={14}/> Mark applied</Button><Button size="sm" variant="ghost" onClick={()=>void updateSuggestion(s.id,"IGNORED")}><X size={14}/> Ignore</Button></div>}</article>)}{result.suggestions.length===0&&<p className="rounded-xl bg-slate-50 p-4 text-sm text-slate-500 dark:bg-slate-950">No suggestions to save yet. Upload a resume with a selectable text layer and add required job skills for a more detailed comparison.</p>}{result.optionalAiInsight&&<div className="rounded-xl bg-violet-50 p-4 text-sm dark:bg-violet-950/40"><p className="font-semibold">Optional AI insight</p><p className="mt-1 whitespace-pre-wrap">{result.optionalAiInsight}</p></div>}</div></CardContent></Card>
    </div>}
    {!loading&&!jobs.length&&<Card><CardContent className="py-14 text-center"><FileSearch size={24} className="mx-auto text-emerald-800 dark:text-emerald-400"/><h2 className="mt-3 text-sm font-semibold">Add a job before analyzing your resume</h2><p className="mt-1 text-xs text-slate-500">Job analysis compares saved job requirements with uploaded resume evidence.</p><Link href="/jobs" className="mt-4 inline-flex text-xs font-semibold text-emerald-800">Open jobs</Link></CardContent></Card>}
  </div>;
}
