"use client";

import { useEffect, useState } from "react";
import { BookOpenCheck, RefreshCw, Save } from "lucide-react";
import { api, errorMessage } from "@/lib/api";
import type { InterviewPreparation, JobOpportunity, Page } from "@/lib/types";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";

export default function InterviewPrepPage(){
  const [jobs,setJobs]=useState<JobOpportunity[]>([]);const [jobId,setJobId]=useState("");const [prep,setPrep]=useState<InterviewPreparation>();const [notes,setNotes]=useState("");const [busy,setBusy]=useState(false);const [saving,setSaving]=useState(false);const [error,setError]=useState("");
  useEffect(()=>{api<Page<JobOpportunity>>("jobs?page=0&size=100&sort=updatedAt&direction=desc").then(page=>{setJobs(page.content);if(page.content[0])setJobId(page.content[0].id);}).catch(e=>setError(errorMessage(e)));},[]);
  useEffect(()=>{if(!jobId)return;setPrep(undefined);api<InterviewPreparation[]>(`jobs/${jobId}/interview-prep`).then(rows=>{if(rows[0]){setPrep(rows[0]);setNotes(rows[0].notes);}}).catch(e=>setError(errorMessage(e)));},[jobId]);
  async function generate(){if(!jobId)return;setBusy(true);setError("");try{const row=await api<InterviewPreparation>(`jobs/${jobId}/interview-prep`,{method:"POST"});setPrep(row);setNotes(row.notes);}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
  async function save(){if(!jobId||!prep)return;setSaving(true);setError("");try{const row=await api<InterviewPreparation>(`jobs/${jobId}/interview-prep/${prep.id}`,{method:"PUT",body:JSON.stringify({notes})});setPrep(row);setNotes(row.notes);}catch(e){setError(errorMessage(e));}finally{setSaving(false);}}
  return <div className="space-y-6">
    <header><p className="text-xs font-semibold text-emerald-800 dark:text-emerald-400">Interview preparation</p><h1 className="mt-1 text-[29px] font-semibold tracking-[-0.04em]">Prepare for the conversation</h1><p className="mt-1.5 text-sm text-slate-500">Build a role-specific topic list and save your own interview notes.</p></header>
    {error&&<p role="alert" className="rounded-xl bg-rose-50 px-4 py-3 text-sm text-rose-700 dark:bg-rose-950/50 dark:text-rose-300">{error}</p>}
    <Card><CardContent className="flex flex-col gap-3 p-4 sm:flex-row sm:items-end"><label className="form-label min-w-0 flex-1">Job<select className="form-select" value={jobId} onChange={e=>setJobId(e.target.value)}>{jobs.map(j=><option key={j.id} value={j.id}>{j.title}</option>)}</select></label><Button onClick={()=>void generate()} disabled={!jobId||busy}><RefreshCw size={15}/>{busy?"Preparing…":"Generate preparation"}</Button></CardContent></Card>
    {prep&&<div className="space-y-4"><div className="grid gap-4 xl:grid-cols-2"><Card><CardContent className="p-5"><h2 className="text-sm font-semibold">Technical topics</h2><div className="mt-3 flex flex-wrap gap-2">{prep.technicalTopics.length?prep.technicalTopics.map(t=><span key={t} className="rounded-full bg-sky-50 px-3 py-1.5 text-xs font-medium text-sky-800 dark:bg-sky-950 dark:text-sky-200">{t}</span>):<p className="text-sm text-slate-500">Add required skills to this job to tailor technical topics.</p>}</div></CardContent></Card><Card><CardContent className="p-5"><h2 className="text-sm font-semibold">System design topics</h2><ul className="mt-3 space-y-2 text-sm text-slate-600 dark:text-slate-300">{prep.systemDesignTopics.map(t=><li key={t} className="flex gap-2"><BookOpenCheck size={15} className="mt-0.5 shrink-0 text-emerald-800 dark:text-emerald-400"/>{t}</li>)}</ul></CardContent></Card></div><Card><CardContent className="p-5"><h2 className="text-sm font-semibold">Possible questions</h2><ol className="mt-3 list-decimal space-y-2 pl-5 text-sm leading-6 text-slate-600 dark:text-slate-300">{prep.possibleQuestions.map(q=><li key={q}>{q}</li>)}</ol></CardContent></Card><Card><CardContent className="p-5"><div className="flex items-center justify-between gap-3"><div><h2 className="text-sm font-semibold">My preparation notes</h2><p className="mt-1 text-xs text-slate-500">Your notes are private to your account.</p></div><Button size="sm" onClick={()=>void save()} disabled={saving}><Save size={14}/>{saving?"Saving…":"Save notes"}</Button></div><textarea maxLength={12000} rows={8} value={notes} onChange={e=>setNotes(e.target.value)} className="form-textarea mt-4" placeholder="Questions to ask, examples to prepare, and points to review…"/></CardContent></Card></div>}
    {!jobs.length&&<Card><CardContent className="py-14 text-center"><p className="text-sm font-semibold">Add a job to prepare for interviews</p><p className="mt-1 text-xs text-slate-500">Preparation notes are attached to the job opportunity.</p></CardContent></Card>}
  </div>;
}
