"use client";

import { useEffect, useState, type FormEvent } from "react";
import { BriefcaseBusiness, ExternalLink, Pencil, Plus, Search, Sparkles, Target, Trash2 } from "lucide-react";
import { api, errorMessage } from "@/lib/api";
import type { Company, JobMatch, JobOpportunity, JobPriority, JobStatus, Page, RankedJob, Resume } from "@/lib/types";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { Modal } from "@/components/ui/modal";

const statuses: JobStatus[] = ["FOUND","INTERESTED","REFERRAL_REQUIRED","APPLIED","OA","INTERVIEW","OFFER","REJECTED"];
const priorities: JobPriority[] = ["LOW","MEDIUM","HIGH","DREAM"];
type JobForm = { companyId: string; title: string; description: string; location: string; employmentType: string; experienceLevel: string; source: string; careerUrl: string; salaryRange: string; skills: string; status: JobStatus; priority: JobPriority };
const emptyForm: JobForm = { companyId:"",title:"",description:"",location:"",employmentType:"",experienceLevel:"",source:"",careerUrl:"",salaryRange:"",skills:"",status:"FOUND",priority:"MEDIUM" };
const label = (value: string) => value.toLowerCase().replaceAll("_"," ").replace(/\b\w/g,letter=>letter.toUpperCase());

function JobEditor({ initial, companies, busy, onCancel, onSave }: { initial?: JobOpportunity; companies: Company[]; busy: boolean; onCancel: () => void; onSave: (data: JobForm) => void }) {
  const [form,setForm]=useState<JobForm>(initial?{companyId:initial.companyId,title:initial.title,description:initial.description,location:initial.location??"",employmentType:initial.employmentType??"",experienceLevel:initial.experienceLevel??"",source:initial.source??"",careerUrl:initial.careerUrl??"",salaryRange:initial.salaryRange??"",skills:initial.skills.join(", "),status:initial.status,priority:initial.priority}:emptyForm);
  function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();onSave(form);}
  return <form onSubmit={submit} className="space-y-4">
    <div className="grid gap-4 sm:grid-cols-2"><label className="form-label">Company<select required className="form-select" value={form.companyId} onChange={e=>setForm({...form,companyId:e.target.value})}><option value="">Choose a company</option>{companies.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="form-label">Job title<Input required maxLength={200} value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="Backend Engineer"/></label></div>
    <label className="form-label">Job description<textarea required maxLength={50000} rows={6} value={form.description} onChange={e=>setForm({...form,description:e.target.value})} className="form-textarea" placeholder="Paste the job details you want to compare with your profile."/></label>
    <label className="form-label">Required skills <span className="font-normal text-slate-400">comma separated</span><Input value={form.skills} onChange={e=>setForm({...form,skills:e.target.value})} placeholder="Java, Spring Boot, AWS"/></label>
    <div className="grid gap-4 sm:grid-cols-2"><label className="form-label">Location<Input maxLength={200} value={form.location} onChange={e=>setForm({...form,location:e.target.value})} placeholder="Remote / Bengaluru"/></label><label className="form-label">Salary range<Input maxLength={120} value={form.salaryRange} onChange={e=>setForm({...form,salaryRange:e.target.value})} placeholder="₹20L–₹28L"/></label></div>
    <div className="grid gap-4 sm:grid-cols-2"><label className="form-label">Employment type<Input maxLength={32} value={form.employmentType} onChange={e=>setForm({...form,employmentType:e.target.value})} placeholder="FULL_TIME"/></label><label className="form-label">Experience level<Input maxLength={32} value={form.experienceLevel} onChange={e=>setForm({...form,experienceLevel:e.target.value})} placeholder="SENIOR"/></label></div>
    <div className="grid gap-4 sm:grid-cols-2"><label className="form-label">Status<select className="form-select" value={form.status} onChange={e=>setForm({...form,status:e.target.value as JobStatus})}>{statuses.map(s=><option key={s} value={s}>{label(s)}</option>)}</select></label><label className="form-label">Priority<select className="form-select" value={form.priority} onChange={e=>setForm({...form,priority:e.target.value as JobPriority})}>{priorities.map(p=><option key={p} value={p}>{label(p)}</option>)}</select></label></div>
    <div className="grid gap-4 sm:grid-cols-2"><label className="form-label">Source<Input maxLength={120} value={form.source} onChange={e=>setForm({...form,source:e.target.value})} placeholder="Company career page"/></label><label className="form-label">Career URL<Input type="url" maxLength={2048} value={form.careerUrl} onChange={e=>setForm({...form,careerUrl:e.target.value})} placeholder="https://..."/></label></div>
    <div className="flex justify-end gap-2 border-t border-slate-100 pt-4 dark:border-slate-800"><Button type="button" variant="secondary" onClick={onCancel}>Cancel</Button><Button type="submit" disabled={busy||companies.length===0}>{busy?"Saving…":initial?"Save changes":"Add opportunity"}</Button></div>
  </form>;
}

export default function JobsPage(){
  const [rows,setRows]=useState<JobOpportunity[]>([]);const [companies,setCompanies]=useState<Company[]>([]);const [resumes,setResumes]=useState<Resume[]>([]);const [ranked,setRanked]=useState<RankedJob[]>([]);
  const [page,setPage]=useState(0);const [pages,setPages]=useState(0);const [total,setTotal]=useState(0);const [search,setSearch]=useState("");const [status,setStatus]=useState("");const [companyId,setCompanyId]=useState("");const [priority,setPriority]=useState("");
  const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [refresh,setRefresh]=useState(0);const [open,setOpen]=useState(false);const [selected,setSelected]=useState<JobOpportunity>();const [match,setMatch]=useState<JobMatch>();const [matching,setMatching]=useState(false);const [matchJob,setMatchJob]=useState<JobOpportunity>();
  const [skillsOpen,setSkillsOpen]=useState(false);const [resumeId,setResumeId]=useState("");const [resumeSkillsText,setResumeSkillsText]=useState("");const [skillsBusy,setSkillsBusy]=useState(false);
  useEffect(()=>{api<Page<Company>>("companies?page=0&size=100&sort=name&direction=asc").then(r=>setCompanies(r.content)).catch(()=>setCompanies([]));},[]);
  useEffect(()=>{api<Page<Resume>>("resumes?page=0&size=100&sort=createdAt&direction=desc").then(r=>setResumes(r.content)).catch(()=>setResumes([]));},[]);
  useEffect(()=>{api<RankedJob[]>("jobs/top?limit=5").then(setRanked).catch(()=>setRanked([]));},[refresh]);
  useEffect(()=>{const timer=window.setTimeout(()=>{setLoading(true);setError("");const q=new URLSearchParams({page:String(page),size:"20",sort:"createdAt",direction:"desc"});if(search.trim())q.set("search",search.trim());if(status)q.set("status",status);if(companyId)q.set("companyId",companyId);if(priority)q.set("priority",priority);api<Page<JobOpportunity>>(`jobs?${q}`).then(r=>{setRows(r.content);setPages(r.totalPages);setTotal(r.totalElements);}).catch(e=>setError(errorMessage(e))).finally(()=>setLoading(false));},130);return()=>window.clearTimeout(timer);},[page,search,status,companyId,priority,refresh]);
  async function save(form:JobForm){setBusy(true);setError("");const payload={...form,location:form.location||null,employmentType:form.employmentType||null,experienceLevel:form.experienceLevel||null,source:form.source||null,careerUrl:form.careerUrl||null,salaryRange:form.salaryRange||null,skills:form.skills.split(",").map(s=>s.trim()).filter(Boolean)};try{await api(selected?`jobs/${selected.id}`:"jobs",{method:selected?"PUT":"POST",body:JSON.stringify(payload)});setOpen(false);setSelected(undefined);setRefresh(v=>v+1);}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
  async function remove(job:JobOpportunity){if(!window.confirm(`Remove ${job.title} from your opportunities?`))return;try{await api(`jobs/${job.id}`,{method:"DELETE"});setRefresh(v=>v+1);}catch(e){setError(errorMessage(e));}}
  async function showMatch(job:JobOpportunity){setMatchJob(job);setMatch(undefined);setMatching(true);try{setMatch(await api<JobMatch>(`jobs/${job.id}/match`));}catch(e){setError(errorMessage(e));}finally{setMatching(false);}}
  async function openResumeSkills(){const id=resumeId||resumes[0]?.id;if(!id)return;setResumeId(id);setSkillsOpen(true);try{const rows=await api<Array<{skill:string}>>(`resumes/${id}/skills`);setResumeSkillsText(rows.map(s=>s.skill).join(", "));}catch(e){setError(errorMessage(e));}}
  async function changeResumeSkills(id:string){setResumeId(id);try{const rows=await api<Array<{skill:string}>>(`resumes/${id}/skills`);setResumeSkillsText(rows.map(s=>s.skill).join(", "));}catch(e){setError(errorMessage(e));}}
  async function saveResumeSkills(){if(!resumeId)return;setSkillsBusy(true);try{await api(`resumes/${resumeId}/skills`,{method:"PUT",body:JSON.stringify({skills:resumeSkillsText.split(",").map(s=>s.trim()).filter(Boolean)})});setSkillsOpen(false);}catch(e){setError(errorMessage(e));}finally{setSkillsBusy(false);}}
  const companyName=(id:string)=>companies.find(c=>c.id===id)?.name??"Company";
  return <div className="space-y-6">
    <header className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-xs font-semibold text-emerald-800 dark:text-emerald-400">Job intelligence</p><h1 className="mt-1 text-[29px] font-semibold tracking-[-0.04em]">Job opportunities</h1><p className="mt-1.5 text-sm text-slate-500">Collect roles, compare them with your skills, and choose what deserves your attention.</p></div><div className="flex gap-2"><Button variant="secondary" onClick={()=>void openResumeSkills()} disabled={!resumes.length}>Resume skills</Button><Button onClick={()=>{setSelected(undefined);setOpen(true);}} disabled={!companies.length}><Plus size={16}/> Add job</Button></div></header>
    {error&&<p role="alert" className="rounded-xl bg-rose-50 px-4 py-3 text-sm text-rose-700 dark:bg-rose-950/50 dark:text-rose-300">{error}</p>}
    <Card><CardContent className="p-5"><div className="mb-4 flex items-center gap-2"><Sparkles size={17} className="text-emerald-700 dark:text-emerald-400"/><div><h2 className="text-sm font-semibold">Recommended opportunities</h2><p className="mt-0.5 text-xs text-slate-500">Ranked using skills (40%), company priority (20%), role (20%), location (10%), and experience (10%).</p></div></div>{ranked.length?<div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{ranked.map(job=><button key={job.id} onClick={()=>{const found=rows.find(r=>r.id===job.id);if(found)void showMatch(found);else api<JobOpportunity>(`jobs/${job.id}`).then(showMatch).catch(e=>setError(errorMessage(e)));}} className="rounded-xl border border-slate-200 p-4 text-left transition hover:border-emerald-300 hover:bg-emerald-50/40 dark:border-slate-800 dark:hover:border-emerald-800 dark:hover:bg-emerald-950/20"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="truncate text-sm font-semibold">{job.title}</p><p className="mt-1 truncate text-xs text-slate-500">{job.companyName??companyName(job.companyId)}{job.location?` · ${job.location}`:""}</p></div><span className="shrink-0 rounded-full bg-emerald-50 px-2 py-1 text-xs font-semibold text-emerald-800 dark:bg-emerald-950 dark:text-emerald-300">{job.rankingScore}%</span></div>{job.reasons.length>0&&<p className="mt-3 line-clamp-2 text-xs text-slate-500">{job.reasons.join(" · ")}</p>}{job.recommendedResume&&<p className="mt-2 text-xs font-medium text-slate-700 dark:text-slate-300">Resume: {job.recommendedResume}</p>}</button>)}</div>:<p className="rounded-xl bg-slate-50 p-5 text-center text-sm text-slate-500 dark:bg-slate-950">Save a few jobs to get a ranked shortlist.</p>}</CardContent></Card>
    <Card><CardContent className="grid gap-3 p-4 sm:grid-cols-2 xl:grid-cols-[minmax(220px,1fr)_190px_190px_160px_auto]"><div className="relative"><Search size={15} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400"/><Input aria-label="Search jobs" placeholder="Search jobs…" className="pl-9" value={search} onChange={e=>{setPage(0);setSearch(e.target.value);}}/></div><select aria-label="Filter by status" className="form-select" value={status} onChange={e=>{setPage(0);setStatus(e.target.value);}}><option value="">All statuses</option>{statuses.map(s=><option key={s} value={s}>{label(s)}</option>)}</select><select aria-label="Filter by company" className="form-select" value={companyId} onChange={e=>{setPage(0);setCompanyId(e.target.value);}}><option value="">All companies</option>{companies.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><select aria-label="Filter by priority" className="form-select" value={priority} onChange={e=>{setPage(0);setPriority(e.target.value);}}><option value="">All priorities</option>{priorities.map(p=><option key={p} value={p}>{label(p)}</option>)}</select><span className="self-center text-xs text-slate-400">{total} {total===1?"job":"jobs"}</span></CardContent></Card>
    <div className="space-y-3">{loading?Array.from({length:4},(_,i)=><Card key={i}><CardContent className="p-5"><div className="h-20 animate-pulse rounded bg-slate-100 dark:bg-slate-800"/></CardContent></Card>):rows.map(job=><Card key={job.id}><CardContent className="flex flex-col gap-4 p-5 lg:flex-row lg:items-center"><div className="grid size-11 shrink-0 place-items-center rounded-xl bg-slate-100 text-slate-700 dark:bg-slate-800 dark:text-slate-200"><BriefcaseBusiness size={20}/></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="text-sm font-semibold">{job.title}</h2><Badge tone={job.status}>{label(job.status)}</Badge><span className="rounded-full bg-slate-100 px-2 py-0.5 text-[10px] font-semibold text-slate-600 dark:bg-slate-800 dark:text-slate-300">{label(job.priority)}</span></div><p className="mt-1 text-xs text-slate-500">{companyName(job.companyId)}{job.location?` · ${job.location}`:""}{job.employmentType?` · ${label(job.employmentType)}`:""}</p>{job.skills.length>0&&<div className="mt-2 flex flex-wrap gap-1.5">{job.skills.slice(0,7).map(s=><span key={s} className="rounded-full border border-slate-200 px-2 py-0.5 text-[10px] text-slate-600 dark:border-slate-700 dark:text-slate-300">{s}</span>)}</div>}</div><div className="flex flex-wrap items-center gap-2"><Button variant="secondary" size="sm" onClick={()=>void showMatch(job)}><Target size={14}/> Match {job.matchScore?`${job.matchScore}%`:"skills"}</Button>{job.careerUrl&&<a href={job.careerUrl} target="_blank" rel="noreferrer" aria-label="Open job posting" className="grid size-9 place-items-center rounded-xl border border-slate-200 text-slate-500 hover:text-emerald-800 dark:border-slate-700"><ExternalLink size={15}/></a>}<Button variant="ghost" size="icon" aria-label={`Edit ${job.title}`} onClick={()=>{setSelected(job);setOpen(true);}}><Pencil size={15}/></Button><Button variant="ghost" size="icon" aria-label={`Remove ${job.title}`} onClick={()=>void remove(job)}><Trash2 size={15}/></Button></div></CardContent></Card>)}
    {!loading&&!rows.length&&<Card><CardContent className="py-16 text-center"><BriefcaseBusiness size={24} className="mx-auto text-emerald-800 dark:text-emerald-400"/><p className="mt-3 text-sm font-semibold">{search||status||companyId||priority?"No jobs match these filters":"Start building your job shortlist"}</p><p className="mt-1 text-xs text-slate-500">Save roles you found manually from public sources or company career pages.</p>{!search&&!status&&!companyId&&!priority&&<Button className="mt-4" size="sm" onClick={()=>{setSelected(undefined);setOpen(true);}} disabled={!companies.length}><Plus size={14}/> Add your first job</Button>}</CardContent></Card>}
    {!loading&&total>0&&<div className="flex items-center justify-between text-xs text-slate-500"><span>Page {page+1} of {Math.max(1,pages)}</span><div className="flex gap-2"><Button variant="secondary" size="sm" disabled={page<=0} onClick={()=>setPage(p=>Math.max(0,p-1))}>Previous</Button><Button variant="secondary" size="sm" disabled={page+1>=pages} onClick={()=>setPage(p=>p+1)}>Next</Button></div></div>}</div>
    <Modal open={open} onClose={()=>{setOpen(false);setSelected(undefined);}} title={selected?"Edit job opportunity":"Add a job opportunity"} description="Keep job details and required skills organized for later comparison.">{companies.length?<JobEditor key={selected?.id??"new-job"} initial={selected} companies={companies} busy={busy} onCancel={()=>setOpen(false)} onSave={save}/>:<p className="text-sm text-slate-500">Add a company before saving a job opportunity.</p>}</Modal>
    <Modal open={skillsOpen} onClose={()=>setSkillsOpen(false)} title="Resume skills" description="Enter skills you have verified are represented in each resume. These are compared with job requirements.">{resumes.length?<div className="space-y-4"><label className="form-label">Resume<select className="form-select" value={resumeId} onChange={e=>void changeResumeSkills(e.target.value)}>{resumes.map(r=><option key={r.id} value={r.id}>{r.label}</option>)}</select></label><label className="form-label">Skills <span className="font-normal text-slate-400">comma separated</span><textarea rows={5} value={resumeSkillsText} onChange={e=>setResumeSkillsText(e.target.value)} className="form-textarea" placeholder="Java, Spring Boot, AWS"/></label><div className="flex justify-end gap-2"><Button variant="secondary" onClick={()=>setSkillsOpen(false)}>Cancel</Button><Button onClick={()=>void saveResumeSkills()} disabled={skillsBusy}>{skillsBusy?"Saving…":"Save skills"}</Button></div></div>:<p className="text-sm text-slate-500">Add a resume before recording its skills.</p>}</Modal>
    <Modal open={Boolean(matchJob)} onClose={()=>{setMatchJob(undefined);setMatch(undefined);}} title={matchJob?`Match: ${matchJob.title}`:"Job match"} description={matchJob?companyName(matchJob.companyId):undefined}>{matching?<p className="py-6 text-sm text-slate-500">Comparing job requirements with your profile and resume skills…</p>:match&&<div className="space-y-4"><div className="rounded-xl bg-emerald-50 p-4 dark:bg-emerald-950/40"><p className="text-3xl font-semibold text-emerald-900 dark:text-emerald-200">{match.score}%</p><p className="mt-1 text-sm font-medium">{match.recommendation}</p></div><div><h3 className="text-xs font-semibold uppercase tracking-wide text-slate-500">Matching skills</h3><div className="mt-2 flex flex-wrap gap-2">{match.matchingSkills.length?match.matchingSkills.map(s=><Badge key={s} tone="REFERRED">{s}</Badge>):<span className="text-sm text-slate-500">No saved skills match yet.</span>}</div></div><div><h3 className="text-xs font-semibold uppercase tracking-wide text-slate-500">Skills to review</h3><div className="mt-2 flex flex-wrap gap-2">{match.missingSkills.length?match.missingSkills.map(s=><Badge key={s} tone="REJECTED">{s}</Badge>):<span className="text-sm text-slate-500">No missing skills from the saved requirements.</span>}</div></div><div className="rounded-xl border border-slate-200 p-3 dark:border-slate-700"><p className="text-xs text-slate-500">Recommended resume</p><p className="mt-1 text-sm font-semibold">{match.recommendedResume??"Add a resume to receive a recommendation"}</p><p className="mt-1 text-xs text-slate-500">{match.resumeReason}</p></div></div>}</Modal>
  </div>;
}
